FROM openjdk:8-jdk

ENV SPRING_PROFILES_ACTIVE=dev
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew bootJar

CMD ["./gradlew", "bootRun"]