server:
  port: 8079

spring:
  jpa:
    properties:
      hibernates:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hs2b;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: