server:
  port: 8080

spring:
  config:
    activate:
      on-profile: real
  profiles:
    include: real-db
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect