DROP DATABASE IF EXISTS hs2b;

CREATE DATABASE hs2b DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE hs2b;

CREATE TABLE lists (
    id INTEGER AUTO_INCREMENT,
    value TEXT,
    PRIMARY KEY (id)
);